// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './italianno.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };

import _0 from './svg/0.tsx';
import _1 from './svg/1.tsx';
import _2 from './svg/2.tsx';
import _3 from './svg/3.tsx';
import _4 from './svg/4.tsx';
import _5 from './svg/5.tsx';
import _6 from './svg/6.tsx';
import _7 from './svg/7.tsx';
import _8 from './svg/8.tsx';
import _9 from './svg/9.tsx';
import _10 from './svg/upper_A.tsx';
import _11 from './svg/upper_B.tsx';
import _12 from './svg/upper_C.tsx';
import _13 from './svg/upper_D.tsx';
import _14 from './svg/upper_E.tsx';
import _15 from './svg/upper_F.tsx';
import _16 from './svg/upper_G.tsx';
import _17 from './svg/upper_H.tsx';
import _18 from './svg/upper_I.tsx';
import _19 from './svg/upper_J.tsx';
import _20 from './svg/upper_K.tsx';
import _21 from './svg/upper_L.tsx';
import _22 from './svg/upper_M.tsx';
import _23 from './svg/upper_N.tsx';
import _24 from './svg/upper_O.tsx';
import _25 from './svg/upper_P.tsx';
import _26 from './svg/upper_Q.tsx';
import _27 from './svg/upper_R.tsx';
import _28 from './svg/upper_S.tsx';
import _29 from './svg/upper_T.tsx';
import _30 from './svg/upper_U.tsx';
import _31 from './svg/upper_V.tsx';
import _32 from './svg/upper_W.tsx';
import _33 from './svg/upper_X.tsx';
import _34 from './svg/upper_Y.tsx';
import _35 from './svg/upper_Z.tsx';
import _36 from './svg/a.tsx';
import _37 from './svg/b.tsx';
import _38 from './svg/c.tsx';
import _39 from './svg/d.tsx';
import _40 from './svg/e.tsx';
import _41 from './svg/f.tsx';
import _42 from './svg/g.tsx';
import _43 from './svg/h.tsx';
import _44 from './svg/i.tsx';
import _45 from './svg/j.tsx';
import _46 from './svg/k.tsx';
import _47 from './svg/l.tsx';
import _48 from './svg/m.tsx';
import _49 from './svg/n.tsx';
import _50 from './svg/o.tsx';
import _51 from './svg/p.tsx';
import _52 from './svg/q.tsx';
import _53 from './svg/r.tsx';
import _54 from './svg/s.tsx';
import _55 from './svg/t.tsx';
import _56 from './svg/u.tsx';
import _57 from './svg/v.tsx';
import _58 from './svg/w.tsx';
import _59 from './svg/x.tsx';
import _60 from './svg/y.tsx';
import _61 from './svg/z.tsx';
import _62 from './svg/U+002e.tsx';
import _63 from './svg/U+002c.tsx';
import _64 from './svg/U+003b.tsx';
import _65 from './svg/U+003a.tsx';
import _66 from './svg/U+0021.tsx';
import _67 from './svg/U+003f.tsx';
import _68 from './svg/U+0027.tsx';
import _69 from './svg/U+0022.tsx';
import _70 from './svg/U+002d.tsx';
import _71 from './svg/U+0028.tsx';
import _72 from './svg/U+0029.tsx';
import _73 from './svg/U+002f.tsx';
import _74 from './svg/U+005c.tsx';
import _75 from './svg/U+0040.tsx';
import _76 from './svg/U+0023.tsx';
import _77 from './svg/U+0024.tsx';
import _78 from './svg/U+0025.tsx';
import _79 from './svg/U+0026.tsx';
import _80 from './svg/U+002a.tsx';
import _81 from './svg/U+002b.tsx';
import _82 from './svg/U+003d.tsx';
import _83 from './svg/U+003c.tsx';
import _84 from './svg/U+003e.tsx';
import _85 from './svg/U+007e.tsx';
import _86 from './svg/U+0060.tsx';
import _87 from './svg/U+005e.tsx';
import _88 from './svg/U+005f.tsx';
import _89 from './svg/U+007c.tsx';

let registered: Promise<void> | null = null;

const bundle = {
  family: 'Italianno',
  lineCap: 'round',
  fontUrl,
  unitsPerEm: 1000,
  ascender: 800,
  descender: -450,
  glyphs: {
  '0': _0,
  '1': _1,
  '2': _2,
  '3': _3,
  '4': _4,
  '5': _5,
  '6': _6,
  '7': _7,
  '8': _8,
  '9': _9,
  'A': _10,
  'B': _11,
  'C': _12,
  'D': _13,
  'E': _14,
  'F': _15,
  'G': _16,
  'H': _17,
  'I': _18,
  'J': _19,
  'K': _20,
  'L': _21,
  'M': _22,
  'N': _23,
  'O': _24,
  'P': _25,
  'Q': _26,
  'R': _27,
  'S': _28,
  'T': _29,
  'U': _30,
  'V': _31,
  'W': _32,
  'X': _33,
  'Y': _34,
  'Z': _35,
  'a': _36,
  'b': _37,
  'c': _38,
  'd': _39,
  'e': _40,
  'f': _41,
  'g': _42,
  'h': _43,
  'i': _44,
  'j': _45,
  'k': _46,
  'l': _47,
  'm': _48,
  'n': _49,
  'o': _50,
  'p': _51,
  'q': _52,
  'r': _53,
  's': _54,
  't': _55,
  'u': _56,
  'v': _57,
  'w': _58,
  'x': _59,
  'y': _60,
  'z': _61,
  '.': _62,
  ',': _63,
  ';': _64,
  ':': _65,
  '!': _66,
  '?': _67,
  '\'': _68,
  '"': _69,
  '-': _70,
  '(': _71,
  ')': _72,
  '/': _73,
  '\\': _74,
  '@': _75,
  '#': _76,
  '$': _77,
  '%': _78,
  '&': _79,
  '*': _80,
  '+': _81,
  '=': _82,
  '<': _83,
  '>': _84,
  '~': _85,
  '`': _86,
  '^': _87,
  '_': _88,
  '|': _89,
  },
  glyphData,
  glyphTimings: {
  '0': 0.517,
  '1': 0.56,
  '2': 0.538,
  '3': 0.698,
  '4': 0.953,
  '5': 0.559,
  '6': 0.727,
  '7': 0.443,
  '8': 0.45,
  '9': 0.58,
  'A': 1.323,
  'B': 1.391,
  'C': 0.501,
  'D': 0.884,
  'E': 0.976,
  'F': 0.972,
  'G': 1.41,
  'H': 1.259,
  'I': 0.581,
  'J': 0.657,
  'K': 1.222,
  'L': 0.63,
  'M': 1.407,
  'N': 1.168,
  'O': 0.901,
  'P': 1.025,
  'Q': 0.918,
  'R': 1.062,
  'S': 0.602,
  'T': 0.882,
  'U': 1.101,
  'V': 1.037,
  'W': 1.407,
  'X': 1.288,
  'Y': 1.101,
  'Z': 0.892,
  'a': 0.524,
  'b': 0.661,
  'c': 0.4,
  'd': 0.845,
  'e': 0.457,
  'f': 0.668,
  'g': 0.748,
  'h': 0.7,
  'i': 0.549,
  'j': 0.493,
  'k': 0.835,
  'l': 0.824,
  'm': 1.259,
  'n': 0.905,
  'o': 0.756,
  'p': 0.76,
  'q': 0.923,
  'r': 0.763,
  's': 0.559,
  't': 0.691,
  'u': 0.58,
  'v': 0.584,
  'w': 0.796,
  'x': 0.595,
  'y': 0.764,
  'z': 0.649,
  '.': 0.022,
  ',': 0.21,
  ';': 0.238,
  ':': 0.186,
  '!': 0.336,
  '?': 0.456,
  '\'': 0.066,
  '"': 0.434,
  '-': 0.055,
  '(': 0.347,
  ')': 0.347,
  '/': 0.284,
  '\\': 0.261,
  '@': 1.261,
  '#': 1.155,
  '$': 1.124,
  '%': 1.321,
  '&': 1.115,
  '*': 0.859,
  '+': 0.404,
  '=': 0.349,
  '<': 0.17,
  '>': 0.308,
  '~': 0.073,
  '`': 0.205,
  '^': 0.237,
  '_': 0,
  '|': 0.214,
  },
  registerFontFace() {
    if (!registered) {
      registered = new FontFace(bundle.family, `url(${fontUrl})`, { featureSettings: "'calt' 0, 'liga' 0" })
        .load()
        .then((loaded) => { document.fonts.add(loaded); });
    }
    return registered;
  },
} as const;

export default bundle;
