// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './parisienne.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };

import _0 from './svg/0.tsx';
import _1 from './svg/1.tsx';
import _2 from './svg/2.tsx';
import _3 from './svg/3.tsx';
import _4 from './svg/4.tsx';
import _5 from './svg/5.tsx';
import _6 from './svg/6.tsx';
import _7 from './svg/7.tsx';
import _8 from './svg/8.tsx';
import _9 from './svg/9.tsx';
import _10 from './svg/upper_A.tsx';
import _11 from './svg/upper_B.tsx';
import _12 from './svg/upper_C.tsx';
import _13 from './svg/upper_D.tsx';
import _14 from './svg/upper_E.tsx';
import _15 from './svg/upper_F.tsx';
import _16 from './svg/upper_G.tsx';
import _17 from './svg/upper_H.tsx';
import _18 from './svg/upper_I.tsx';
import _19 from './svg/upper_J.tsx';
import _20 from './svg/upper_K.tsx';
import _21 from './svg/upper_L.tsx';
import _22 from './svg/upper_M.tsx';
import _23 from './svg/upper_N.tsx';
import _24 from './svg/upper_O.tsx';
import _25 from './svg/upper_P.tsx';
import _26 from './svg/upper_Q.tsx';
import _27 from './svg/upper_R.tsx';
import _28 from './svg/upper_S.tsx';
import _29 from './svg/upper_T.tsx';
import _30 from './svg/upper_U.tsx';
import _31 from './svg/upper_V.tsx';
import _32 from './svg/upper_W.tsx';
import _33 from './svg/upper_X.tsx';
import _34 from './svg/upper_Y.tsx';
import _35 from './svg/upper_Z.tsx';
import _36 from './svg/a.tsx';
import _37 from './svg/b.tsx';
import _38 from './svg/c.tsx';
import _39 from './svg/d.tsx';
import _40 from './svg/e.tsx';
import _41 from './svg/f.tsx';
import _42 from './svg/g.tsx';
import _43 from './svg/h.tsx';
import _44 from './svg/i.tsx';
import _45 from './svg/j.tsx';
import _46 from './svg/k.tsx';
import _47 from './svg/l.tsx';
import _48 from './svg/m.tsx';
import _49 from './svg/n.tsx';
import _50 from './svg/o.tsx';
import _51 from './svg/p.tsx';
import _52 from './svg/q.tsx';
import _53 from './svg/r.tsx';
import _54 from './svg/s.tsx';
import _55 from './svg/t.tsx';
import _56 from './svg/u.tsx';
import _57 from './svg/v.tsx';
import _58 from './svg/w.tsx';
import _59 from './svg/x.tsx';
import _60 from './svg/y.tsx';
import _61 from './svg/z.tsx';
import _62 from './svg/U+002e.tsx';
import _63 from './svg/U+002c.tsx';
import _64 from './svg/U+003b.tsx';
import _65 from './svg/U+003a.tsx';
import _66 from './svg/U+0021.tsx';
import _67 from './svg/U+003f.tsx';
import _68 from './svg/U+0027.tsx';
import _69 from './svg/U+0022.tsx';
import _70 from './svg/U+002d.tsx';
import _71 from './svg/U+0028.tsx';
import _72 from './svg/U+0029.tsx';
import _73 from './svg/U+002f.tsx';
import _74 from './svg/U+005c.tsx';
import _75 from './svg/U+0040.tsx';
import _76 from './svg/U+0023.tsx';
import _77 from './svg/U+0024.tsx';
import _78 from './svg/U+0025.tsx';
import _79 from './svg/U+0026.tsx';
import _80 from './svg/U+002a.tsx';
import _81 from './svg/U+002b.tsx';
import _82 from './svg/U+003d.tsx';
import _83 from './svg/U+003c.tsx';
import _84 from './svg/U+003e.tsx';
import _85 from './svg/U+007e.tsx';
import _86 from './svg/U+0060.tsx';
import _87 from './svg/U+005e.tsx';
import _88 from './svg/U+005f.tsx';
import _89 from './svg/U+007c.tsx';

let registered: Promise<void> | null = null;

const bundle = {
  family: 'Parisienne',
  lineCap: 'round',
  fontUrl,
  unitsPerEm: 2048,
  ascender: 1875,
  descender: -915,
  glyphs: {
  '0': _0,
  '1': _1,
  '2': _2,
  '3': _3,
  '4': _4,
  '5': _5,
  '6': _6,
  '7': _7,
  '8': _8,
  '9': _9,
  'A': _10,
  'B': _11,
  'C': _12,
  'D': _13,
  'E': _14,
  'F': _15,
  'G': _16,
  'H': _17,
  'I': _18,
  'J': _19,
  'K': _20,
  'L': _21,
  'M': _22,
  'N': _23,
  'O': _24,
  'P': _25,
  'Q': _26,
  'R': _27,
  'S': _28,
  'T': _29,
  'U': _30,
  'V': _31,
  'W': _32,
  'X': _33,
  'Y': _34,
  'Z': _35,
  'a': _36,
  'b': _37,
  'c': _38,
  'd': _39,
  'e': _40,
  'f': _41,
  'g': _42,
  'h': _43,
  'i': _44,
  'j': _45,
  'k': _46,
  'l': _47,
  'm': _48,
  'n': _49,
  'o': _50,
  'p': _51,
  'q': _52,
  'r': _53,
  's': _54,
  't': _55,
  'u': _56,
  'v': _57,
  'w': _58,
  'x': _59,
  'y': _60,
  'z': _61,
  '.': _62,
  ',': _63,
  ';': _64,
  ':': _65,
  '!': _66,
  '?': _67,
  '\'': _68,
  '"': _69,
  '-': _70,
  '(': _71,
  ')': _72,
  '/': _73,
  '\\': _74,
  '@': _75,
  '#': _76,
  '$': _77,
  '%': _78,
  '&': _79,
  '*': _80,
  '+': _81,
  '=': _82,
  '<': _83,
  '>': _84,
  '~': _85,
  '`': _86,
  '^': _87,
  '_': _88,
  '|': _89,
  },
  glyphData,
  glyphTimings: {
  '0': 1.496,
  '1': 0.893,
  '2': 1.877,
  '3': 1.646,
  '4': 1.658,
  '5': 1.892,
  '6': 1.935,
  '7': 1.33,
  '8': 2.074,
  '9': 1.925,
  'A': 3.091,
  'B': 2.888,
  'C': 1.655,
  'D': 2.581,
  'E': 1.957,
  'F': 3.154,
  'G': 2.636,
  'H': 3.766,
  'I': 2.154,
  'J': 2.533,
  'K': 3.33,
  'L': 2.612,
  'M': 3.395,
  'N': 2.799,
  'O': 2.067,
  'P': 2.367,
  'Q': 2.791,
  'R': 2.893,
  'S': 2.449,
  'T': 2.023,
  'U': 2.648,
  'V': 2.361,
  'W': 3.234,
  'X': 3.766,
  'Y': 3.387,
  'Z': 3.069,
  'a': 1.277,
  'b': 1.41,
  'c': 0.807,
  'd': 1.297,
  'e': 1.169,
  'f': 1.656,
  'g': 1.961,
  'h': 1.746,
  'i': 0.568,
  'j': 1.475,
  'k': 2.137,
  'l': 1.183,
  'm': 1.601,
  'n': 1.189,
  'o': 1.198,
  'p': 1.344,
  'q': 1.813,
  'r': 0.579,
  's': 0.975,
  't': 1.263,
  'u': 1.036,
  'v': 0.686,
  'w': 1.374,
  'x': 1.317,
  'y': 1.918,
  'z': 1.782,
  '.': 0.001,
  ',': 0.087,
  ';': 0.232,
  ':': 0.152,
  '!': 0.602,
  '?': 1.072,
  '\'': 0.159,
  '"': 0.466,
  '-': 0.169,
  '(': 0.738,
  ')': 0.737,
  '/': 0.686,
  '\\': 0.523,
  '@': 2.543,
  '#': 1.738,
  '$': 2.619,
  '%': 2.334,
  '&': 2.262,
  '*': 0.971,
  '+': 0.573,
  '=': 0.54,
  '<': 0.325,
  '>': 0.325,
  '~': 0.225,
  '`': 0.249,
  '^': 0.406,
  '_': 0.212,
  '|': 0.648,
  },
  registerFontFace() {
    if (!registered) {
      registered = new FontFace(bundle.family, `url(${fontUrl})`, { featureSettings: "'calt' 0, 'liga' 0" })
        .load()
        .then((loaded) => { document.fonts.add(loaded); });
    }
    return registered;
  },
} as const;

export default bundle;
