// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './caveat.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };

let registered: Promise<void> | null = null;

const bundle = {
  family: 'Caveat',
  lineCap: 'round',
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'Caveat'; src: url(${fontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 960,
  descender: -300,
  glyphData,
  registerFontFace() {
    if (!registered) {
      registered = new FontFace(bundle.family, `url(${fontUrl})`, { featureSettings: "'calt' 0, 'liga' 0" })
        .load()
        .then((loaded) => { document.fonts.add(loaded); });
    }
    return registered;
  },
} as const;

export default bundle;
